spring:
  kafka:
    listener:
      missing-topics-fatal: false
    consumer:
      auto-commit-interval: 1000
      group-id: logdowngroup1
      bootstrap-servers: node1:9092,node2:9092,node3:9092
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        rebalance:
          backoff:
            ms: 2000
          max:
            retries: 10
    producer:
      bootstrap-servers: node1:9092,node2:9092,node3:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: 0
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      properties:
        metadata:
          broker:
            list: node1:9092,node2:9092,node3:9092
        message:
          send:
            max:
              retries: 3
        linger:
          ms: 1
        ssl:
          client:
            auth: required